language: ruby
rvm:
 - "2.2.3"

before_script:
 - mysql -e 'create database syllabus_creator_test;' -uroot
 - cp config/examples/secrets.yml config/secrets.yml

script:
 - bundle exec rake db:test:prepare
 - bundle exec rspec spec
