default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: syllabus_creator_development

test:
  <<: *default
  database: syllabus_creator_test

